---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <matthew.watkins@linuxfoundation.org>

# Markdownlint configuration file

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

MD013: false
