---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <matthew.watkins@linuxfoundation.org>

name: "Nexus Upload"
description: "Nexus Upload Action"

inputs:
  nexus_username:
    description: "Nexus username"
    required: true
  nexus_password:
    description: "Nexus user password"
    required: true
  nexus_server:
    description: "Nexus server name"
    required: true
  nexus_repository:
    description: "Nexus repository name"
    required: true
  upload_directory:
    description: "Directory containing files to upload"
    required: false
  filename_suffix:
    description: "File extension to match"
    required: false

  # Not implemented yet, this parameter may be superfluous
  # repository_format:
  #   description: "Nexus repository format"
  #   required: false

outputs:
  successes:
    description: "Number of successful uploads"
    value: ${{ steps.nexus-upload.outputs.successes }}
  failures:
    description: "Number of failed uploads"
    value: ${{ steps.nexus-upload.outputs.failures }}
  errors:
    description: "Occurence of errors [true|false]"
    value: ${{ steps.nexus-upload.outputs.errors }}

runs:
  using: "composite"
  steps:
    - name: "Set GitHub Path"
      run: |
        # Set $GITHUB_ACTION_PATH to GITHUB_PATH
        echo "$GITHUB_ACTION_PATH" >> "$GITHUB_PATH"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: "Retrieve shell script"
    #   run: |
    #     wget \
    #       https://raw.githubusercontent.com/lfit/releng-nexus-upload/main/nexus-upload.sh
    #     chmod a+x ./nexus-upload.sh
    #   shell: bash
    #   env:
    #     GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: "Display inputs"
      run: |
        # Echo working variables to console
        echo "Nexus username: $NEXUS_USERNAME"
        echo "Nexus server: $NEXUS_SERVER"
        echo "Nexus repository: $NEXUS_REPOSITORY"
        if [ -n "$UPLOAD_DIRECTORY" ]; then
          echo "Upload directory: $UPLOAD_DIRECTORY"
        fi
        if [ -n "$FILENAME_SUFFIX" ]; then
          echo "Filename suffix: *$FILENAME_SUFFIX"
        fi
        # No implemented yet; may be superflouous
        # if [ -n "$REPOSITORY_FORMAT" ]; then
        #   echo "Repository format: $REPOSITORY_FORMAT"
        # fi
      shell: bash
      env:
        NEXUS_USERNAME: ${{ inputs.nexus_username }}
        NEXUS_PASSWORD: ${{ inputs.nexus_password }}
        NEXUS_SERVER: ${{ inputs.nexus_server }}
        NEXUS_REPOSITORY: ${{ inputs.nexus_repository }}
        UPLOAD_DIRECTORY: ${{ inputs.upload_directory }}
        FILENAME_SUFFIX: ${{ inputs.filename_suffix }}
        # REPOSITORY_FORMAT: ${{ inputs.repository_format }}

    - name: "Uploading to Nexus"
      id: nexus-upload
      run: |
        # Upload to Nexus
        NEXUS_URL="https://$NEXUS_SERVER/repository/$NEXUS_REPOSITORY"
        SCRIPT_FLAGS=""
        if [ -n "$FILENAME_SUFFIX" ]; then
          SCRIPT_FLAGS="$SCRIPT_FLAGS -e $FILENAME_SUFFIX"
        fi
        if [ -n "$UPLOAD_DIRECTORY" ]; then
          SCRIPT_FLAGS="$SCRIPT_FLAGS -d $UPLOAD_DIRECTORY"
        fi
        echo "Running: nexus-upload.sh -s $NEXUS_URL $SCRIPT_FLAGS"
        source nexus-upload.sh -s "$NEXUS_URL" $SCRIPT_FLAGS
      shell: bash
      env:
        NEXUS_USERNAME: ${{ inputs.nexus_username }}
        NEXUS_PASSWORD: ${{ inputs.nexus_password }}
        NEXUS_SERVER: ${{ inputs.nexus_server }}
        NEXUS_REPOSITORY: ${{ inputs.nexus_repository }}
        UPLOAD_DIRECTORY: ${{ inputs.upload_directory }}
        FILENAME_SUFFIX: ${{ inputs.filename_suffix }}
        # REPOSITORY_FORMAT: ${{ inputs.repository_format }}
