---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <matthew.watkins@linuxfoundation.org>

name: "Nexus Upload"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Create test file to upload"
        run: |
          # if necessary, create folder and file to upload
          if [ ! -d files ]; then
            mkdir files
          fi
          DATETIME=$(date '+%Y%m%d-%H%M')
          echo "Test file $DATETIME" > "files/upload-$DATETIME.txt"

      - name: "Nexus Upload"
        id: nexus-upload
        # ToDo: change/update the line below when testing is completed
        uses: ModeSevenIndustrialSolutions/nexus-upload-action@v0.0.27
        with:
          nexus_server: nexus3.o-ran-sc.org
          nexus_username: admin
          nexus_password: ${{ secrets.nexus_password }} # Repository secret
          nexus_repository: testing
          upload_directory: files
          filename_suffix: .txt # Optional
          # Not implemented
          # repository_format: raw

      - name: "Show outputs"
        run: |
          # Report outputs
          echo "ERRORS: ${{ steps.nexus-upload.outputs.ERRORS }}"
          echo "SUCCESSES: ${{ steps.nexus-upload.outputs.SUCCESSES }}"
          echo "FAILURES: ${{ steps.nexus-upload.outputs.FAILURES }}"
