---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <matthew.watkins@linuxfoundation.org>

name: "Nexus Upload"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Nexus Upload"
        uses: ModeSevenIndustrialSolutions/nexus-upload-action@v0.0.14
        with:
          nexus_server: nexus3.o-ran-sc.org
          nexus_username: admin
          nexus_password: ${{ secrets.nexus_password }} # Repository secret
          nexus_repository: datasets
          upload_directory: files # Optional
          filename_suffix: .txt # Optional
          # repository_format: raw # Not implemented yet
